import type { ConditionField } from '@/types/permissionRules';

export interface FieldInfo {
  label: string;
  category: string;
  description: string;
  examples: string[];
  valueType: 'text' | 'number' | 'date' | 'boolean' | 'select' | 'multi-select';
  options?: { value: string; label: string }[];
  tooltip: string;
}

export const fieldInfoMap: Record<ConditionField, FieldInfo> = {
  // User Fields
  'user.role': {
    label: 'User Role',
    category: 'User',
    description: 'The role assigned to the user',
    examples: ['admin', 'project_manager', 'client'],
    valueType: 'select',
    options: [
      { value: 'super_admin', label: 'Super Admin' },
      { value: 'admin', label: 'Admin' },
      { value: 'project_manager', label: 'Project Manager' },
      { value: 'sub_contractor', label: 'Sub-Contractor' },
      { value: 'consultant', label: 'Consultant' },
      { value: 'professional', label: 'Professional' },
      { value: 'client', label: 'Client' },
    ],
    tooltip: 'Check if the user has a specific role. Roles determine what features and data a user can access.',
  },
  'user.id': {
    label: 'User ID',
    category: 'User',
    description: 'The unique identifier of the user',
    examples: ['user-123', 'usr_abc456'],
    valueType: 'text',
    tooltip: 'Match a specific user by their unique ID. Useful for granting permissions to individual users.',
  },
  'user.email': {
    label: 'User Email',
    category: 'User',
    description: 'The email address of the user',
    examples: ['john@example.com', '@company.com'],
    valueType: 'text',
    tooltip: 'Check if the user\'s email matches a pattern. Use "contains" operator to match email domains.',
  },
  'user.name': {
    label: 'User Name',
    category: 'User',
    description: 'The full name of the user',
    examples: ['John Smith', 'Jane'],
    valueType: 'text',
    tooltip: 'Match users by their name. Use "contains" to find partial matches.',
  },
  'user.companyId': {
    label: 'User Company',
    category: 'User',
    description: 'The company the user belongs to',
    examples: ['company-123', 'acme-corp'],
    valueType: 'text',
    tooltip: 'Check if the user belongs to a specific company. Useful for company-wide permissions.',
  },
  'user.department': {
    label: 'User Department',
    category: 'User',
    description: 'The department the user works in',
    examples: ['Sales', 'Engineering', 'Operations'],
    valueType: 'text',
    tooltip: 'Filter users by their department. Useful for department-specific access control.',
  },
  'user.hasProjectAccess': {
    label: 'Has Project Access',
    category: 'User',
    description: 'Whether the user has access to a project',
    examples: ['true', 'false'],
    valueType: 'boolean',
    tooltip: 'Check if the user has been granted access to a specific project.',
  },
  'user.isActive': {
    label: 'User Is Active',
    category: 'User',
    description: 'Whether the user account is active',
    examples: ['true', 'false'],
    valueType: 'boolean',
    tooltip: 'Check if the user account is currently active. Inactive users typically cannot access the system.',
  },
  'user.createdAt': {
    label: 'User Created Date',
    category: 'User',
    description: 'When the user account was created',
    examples: ['2024-01-01', '2024-12-31'],
    valueType: 'date',
    tooltip: 'Filter users by when their account was created. Useful for time-based permissions.',
  },
  'user.lastLoginAt': {
    label: 'Last Login Date',
    category: 'User',
    description: 'When the user last logged in',
    examples: ['2024-12-01', '2024-12-18'],
    valueType: 'date',
    tooltip: 'Check when the user last accessed the system. Useful for security and access policies.',
  },
  // Entity Fields
  'entity.type': {
    label: 'Entity Type',
    category: 'Entity',
    description: 'The type of entity (file, project, invoice, etc.)',
    examples: ['file', 'project', 'invoice'],
    valueType: 'select',
    options: [
      { value: 'file', label: 'File' },
      { value: 'project', label: 'Project' },
      { value: 'company', label: 'Company' },
      { value: 'contact', label: 'Contact' },
      { value: 'opportunity', label: 'Opportunity' },
      { value: 'invoice', label: 'Invoice' },
      { value: 'estimate', label: 'Estimate' },
      { value: 'message', label: 'Message' },
      { value: 'email', label: 'Email' },
    ],
    tooltip: 'Check the type of entity being accessed. This helps apply different rules to different entity types.',
  },
  'entity.id': {
    label: 'Entity ID',
    category: 'Entity',
    description: 'The unique identifier of the entity',
    examples: ['entity-123', 'file-456'],
    valueType: 'text',
    tooltip: 'Match a specific entity by its unique ID. Use for entity-specific permissions.',
  },
  'entity.name': {
    label: 'Entity Name',
    category: 'Entity',
    description: 'The name of the entity',
    examples: ['Project Alpha', 'Invoice #1234'],
    valueType: 'text',
    tooltip: 'Match entities by their name. Use "contains" for partial matches.',
  },
  'entity.projectId': {
    label: 'Entity Project',
    category: 'Entity',
    description: 'The project the entity belongs to',
    examples: ['project-123', 'proj_abc'],
    valueType: 'text',
    tooltip: 'Check if the entity is associated with a specific project.',
  },
  'entity.companyId': {
    label: 'Entity Company',
    category: 'Entity',
    description: 'The company the entity belongs to',
    examples: ['company-123', 'acme-corp'],
    valueType: 'text',
    tooltip: 'Check if the entity belongs to a specific company.',
  },
  'entity.isClientVisible': {
    label: 'Is Client Visible',
    category: 'Entity',
    description: 'Whether the entity is visible to clients',
    examples: ['true', 'false'],
    valueType: 'boolean',
    tooltip: 'Check if the entity is marked as visible to clients. Used for client portal access control.',
  },
  'entity.assignedUserId': {
    label: 'Assigned User',
    category: 'Entity',
    description: 'The user assigned to the entity',
    examples: ['user-123', 'usr_abc'],
    valueType: 'text',
    tooltip: 'Check if a specific user is assigned to this entity.',
  },
  'entity.status': {
    label: 'Entity Status',
    category: 'Entity',
    description: 'The current status of the entity',
    examples: ['active', 'completed', 'archived'],
    valueType: 'select',
    options: [
      { value: 'active', label: 'Active' },
      { value: 'pending', label: 'Pending' },
      { value: 'completed', label: 'Completed' },
      { value: 'archived', label: 'Archived' },
      { value: 'cancelled', label: 'Cancelled' },
    ],
    tooltip: 'Check the status of the entity. Different statuses may have different permission requirements.',
  },
  'entity.createdAt': {
    label: 'Entity Created Date',
    category: 'Entity',
    description: 'When the entity was created',
    examples: ['2024-01-01', '2024-12-31'],
    valueType: 'date',
    tooltip: 'Filter entities by creation date. Useful for time-based access rules.',
  },
  'entity.updatedAt': {
    label: 'Entity Updated Date',
    category: 'Entity',
    description: 'When the entity was last updated',
    examples: ['2024-01-01', '2024-12-31'],
    valueType: 'date',
    tooltip: 'Check when the entity was last modified. Useful for tracking recent changes.',
  },
  'entity.priority': {
    label: 'Entity Priority',
    category: 'Entity',
    description: 'The priority level of the entity',
    examples: ['1', '5', '10'],
    valueType: 'number',
    tooltip: 'Check the priority level. Higher numbers typically mean higher priority.',
  },
  // File Fields
  'file.projectId': {
    label: 'File Project',
    category: 'File',
    description: 'The project the file belongs to',
    examples: ['project-123', 'proj_abc'],
    valueType: 'text',
    tooltip: 'Check if the file is associated with a specific project.',
  },
  'file.name': {
    label: 'File Name',
    category: 'File',
    description: 'The name of the file',
    examples: ['report.pdf', 'contract.docx'],
    valueType: 'text',
    tooltip: 'Match files by their name. Use "contains" to match partial filenames or extensions.',
  },
  'file.type': {
    label: 'File Type',
    category: 'File',
    description: 'The file extension or MIME type',
    examples: ['pdf', 'docx', 'image/png'],
    valueType: 'select',
    options: [
      { value: 'pdf', label: 'PDF' },
      { value: 'docx', label: 'Word Document' },
      { value: 'xlsx', label: 'Excel Spreadsheet' },
      { value: 'png', label: 'PNG Image' },
      { value: 'jpg', label: 'JPEG Image' },
      { value: 'zip', label: 'ZIP Archive' },
    ],
    tooltip: 'Check the file type or extension. Useful for restricting access to certain file types.',
  },
  'file.size': {
    label: 'File Size',
    category: 'File',
    description: 'The size of the file in bytes',
    examples: ['1048576', '5242880'],
    valueType: 'number',
    tooltip: 'Check the file size. Use "greater_than" or "less_than" to set size limits.',
  },
  'file.isClientVisible': {
    label: 'File Client Visible',
    category: 'File',
    description: 'Whether the file is visible to clients',
    examples: ['true', 'false'],
    valueType: 'boolean',
    tooltip: 'Check if the file is marked as visible to clients in the client portal.',
  },
  'file.ownerId': {
    label: 'File Owner',
    category: 'File',
    description: 'The user who owns the file',
    examples: ['user-123', 'usr_abc'],
    valueType: 'text',
    tooltip: 'Check if a specific user owns the file. Owners typically have full access.',
  },
  'file.uploadedAt': {
    label: 'File Upload Date',
    category: 'File',
    description: 'When the file was uploaded',
    examples: ['2024-01-01', '2024-12-31'],
    valueType: 'date',
    tooltip: 'Filter files by upload date. Useful for time-based access policies.',
  },
  'file.category': {
    label: 'File Category',
    category: 'File',
    description: 'The category of the file',
    examples: ['contracts', 'reports', 'photos'],
    valueType: 'text',
    tooltip: 'Match files by their category. Helps organize and control access to file groups.',
  },
  'file.tags': {
    label: 'File Tags',
    category: 'File',
    description: 'Tags associated with the file',
    examples: ['confidential', 'urgent', 'draft'],
    valueType: 'text',
    tooltip: 'Check if the file has specific tags. Use "contains" to match any tag.',
  },
  // Project Fields
  'project.clientCompanyId': {
    label: 'Project Client Company',
    category: 'Project',
    description: 'The client company for the project',
    examples: ['company-123', 'acme-corp'],
    valueType: 'text',
    tooltip: 'Check if the project is for a specific client company.',
  },
  'project.name': {
    label: 'Project Name',
    category: 'Project',
    description: 'The name of the project',
    examples: ['Office Renovation', 'New Building'],
    valueType: 'text',
    tooltip: 'Match projects by their name. Use "contains" for partial matches.',
  },
  'project.assignedManagerId': {
    label: 'Project Manager',
    category: 'Project',
    description: 'The project manager assigned to the project',
    examples: ['user-123', 'usr_abc'],
    valueType: 'text',
    tooltip: 'Check if a specific user is the project manager. Project managers typically have full access.',
  },
  'project.status': {
    label: 'Project Status',
    category: 'Project',
    description: 'The current status of the project',
    examples: ['planning', 'in_progress', 'completed'],
    valueType: 'select',
    options: [
      { value: 'planning', label: 'Planning' },
      { value: 'in_progress', label: 'In Progress' },
      { value: 'on_hold', label: 'On Hold' },
      { value: 'completed', label: 'Completed' },
      { value: 'cancelled', label: 'Cancelled' },
    ],
    tooltip: 'Check the project status. Different statuses may have different permission requirements.',
  },
  'project.budget': {
    label: 'Project Budget',
    category: 'Project',
    description: 'The budget allocated to the project',
    examples: ['50000', '100000'],
    valueType: 'number',
    tooltip: 'Check the project budget. Use "greater_than" or "less_than" to set budget thresholds.',
  },
  'project.startDate': {
    label: 'Project Start Date',
    category: 'Project',
    description: 'When the project starts',
    examples: ['2024-01-01', '2024-12-31'],
    valueType: 'date',
    tooltip: 'Check the project start date. Useful for time-based access rules.',
  },
  'project.endDate': {
    label: 'Project End Date',
    category: 'Project',
    description: 'When the project is scheduled to end',
    examples: ['2024-12-31', '2025-06-30'],
    valueType: 'date',
    tooltip: 'Check the project end date. Useful for determining if a project is active.',
  },
  'project.progress': {
    label: 'Project Progress',
    category: 'Project',
    description: 'The completion percentage of the project',
    examples: ['0', '50', '100'],
    valueType: 'number',
    tooltip: 'Check the project progress percentage (0-100). Use to grant access based on completion.',
  },
  'project.priority': {
    label: 'Project Priority',
    category: 'Project',
    description: 'The priority level of the project',
    examples: ['1', '5', '10'],
    valueType: 'number',
    tooltip: 'Check the project priority level. Higher numbers typically mean higher priority.',
  },
  'project.isActive': {
    label: 'Project Is Active',
    category: 'Project',
    description: 'Whether the project is currently active',
    examples: ['true', 'false'],
    valueType: 'boolean',
    tooltip: 'Check if the project is currently active. Inactive projects may have restricted access.',
  },
  // Opportunity Fields
  'opportunity.stage': {
    label: 'Opportunity Stage',
    category: 'Opportunity',
    description: 'The current stage of the opportunity',
    examples: ['lead', 'qualified', 'proposal'],
    valueType: 'select',
    options: [
      { value: 'lead', label: 'Lead' },
      { value: 'qualified', label: 'Qualified' },
      { value: 'proposal', label: 'Proposal' },
      { value: 'negotiation', label: 'Negotiation' },
      { value: 'won', label: 'Won' },
      { value: 'lost', label: 'Lost' },
    ],
    tooltip: 'Check the opportunity stage in the sales pipeline.',
  },
  'opportunity.value': {
    label: 'Opportunity Value',
    category: 'Opportunity',
    description: 'The monetary value of the opportunity',
    examples: ['10000', '50000', '100000'],
    valueType: 'number',
    tooltip: 'Check the opportunity value. Use "greater_than" or "less_than" to set value thresholds.',
  },
  'opportunity.probability': {
    label: 'Opportunity Probability',
    category: 'Opportunity',
    description: 'The probability of winning the opportunity (0-100)',
    examples: ['25', '50', '75'],
    valueType: 'number',
    tooltip: 'Check the win probability percentage. Higher probabilities may have different access rules.',
  },
  'opportunity.expectedCloseDate': {
    label: 'Expected Close Date',
    category: 'Opportunity',
    description: 'When the opportunity is expected to close',
    examples: ['2024-12-31', '2025-03-31'],
    valueType: 'date',
    tooltip: 'Check the expected close date. Useful for time-based access rules.',
  },
  'opportunity.source': {
    label: 'Opportunity Source',
    category: 'Opportunity',
    description: 'Where the opportunity came from',
    examples: ['website', 'referral', 'cold_call'],
    valueType: 'select',
    options: [
      { value: 'website', label: 'Website' },
      { value: 'referral', label: 'Referral' },
      { value: 'cold_call', label: 'Cold Call' },
      { value: 'email', label: 'Email Campaign' },
      { value: 'social_media', label: 'Social Media' },
    ],
    tooltip: 'Check the source of the opportunity. Useful for tracking and access control.',
  },
  'opportunity.status': {
    label: 'Opportunity Status',
    category: 'Opportunity',
    description: 'The current status of the opportunity',
    examples: ['open', 'won', 'lost'],
    valueType: 'select',
    options: [
      { value: 'open', label: 'Open' },
      { value: 'won', label: 'Won' },
      { value: 'lost', label: 'Lost' },
      { value: 'abandoned', label: 'Abandoned' },
    ],
    tooltip: 'Check if the opportunity is open, won, or lost.',
  },
  // Invoice Fields
  'invoice.amount': {
    label: 'Invoice Amount',
    category: 'Invoice',
    description: 'The total amount of the invoice',
    examples: ['1000', '5000', '10000'],
    valueType: 'number',
    tooltip: 'Check the invoice amount. Use "greater_than" or "less_than" to set amount thresholds.',
  },
  'invoice.status': {
    label: 'Invoice Status',
    category: 'Invoice',
    description: 'The current status of the invoice',
    examples: ['draft', 'sent', 'paid'],
    valueType: 'select',
    options: [
      { value: 'draft', label: 'Draft' },
      { value: 'sent', label: 'Sent' },
      { value: 'paid', label: 'Paid' },
      { value: 'overdue', label: 'Overdue' },
      { value: 'cancelled', label: 'Cancelled' },
    ],
    tooltip: 'Check the invoice status. Different statuses may have different visibility rules.',
  },
  'invoice.dueDate': {
    label: 'Invoice Due Date',
    category: 'Invoice',
    description: 'When the invoice is due',
    examples: ['2024-12-31', '2025-01-15'],
    valueType: 'date',
    tooltip: 'Check the invoice due date. Useful for time-based access and reminders.',
  },
  'invoice.projectId': {
    label: 'Invoice Project',
    category: 'Invoice',
    description: 'The project the invoice is for',
    examples: ['project-123', 'proj_abc'],
    valueType: 'text',
    tooltip: 'Check if the invoice is associated with a specific project.',
  },
  'invoice.companyId': {
    label: 'Invoice Company',
    category: 'Invoice',
    description: 'The company the invoice is for',
    examples: ['company-123', 'acme-corp'],
    valueType: 'text',
    tooltip: 'Check if the invoice is for a specific company.',
  },
  'invoice.isPaid': {
    label: 'Invoice Is Paid',
    category: 'Invoice',
    description: 'Whether the invoice has been paid',
    examples: ['true', 'false'],
    valueType: 'boolean',
    tooltip: 'Check if the invoice has been paid. Paid invoices may have different access rules.',
  },
  // Company Fields
  'company.type': {
    label: 'Company Type',
    category: 'Company',
    description: 'The type of company',
    examples: ['client', 'contractor', 'supplier'],
    valueType: 'select',
    options: [
      { value: 'client', label: 'Client' },
      { value: 'contractor', label: 'Contractor' },
      { value: 'supplier', label: 'Supplier' },
      { value: 'consultant', label: 'Consultant' },
    ],
    tooltip: 'Check the type of company. Different company types may have different access levels.',
  },
  'company.industry': {
    label: 'Company Industry',
    category: 'Company',
    description: 'The industry the company operates in',
    examples: ['construction', 'retail', 'technology'],
    valueType: 'text',
    tooltip: 'Match companies by their industry. Useful for industry-specific access rules.',
  },
  'company.size': {
    label: 'Company Size',
    category: 'Company',
    description: 'The size of the company',
    examples: ['small', 'medium', 'large'],
    valueType: 'select',
    options: [
      { value: 'small', label: 'Small (1-50)' },
      { value: 'medium', label: 'Medium (51-200)' },
      { value: 'large', label: 'Large (201+)' },
    ],
    tooltip: 'Check the company size. Useful for tiered access based on company size.',
  },
  'company.isActive': {
    label: 'Company Is Active',
    category: 'Company',
    description: 'Whether the company is active',
    examples: ['true', 'false'],
    valueType: 'boolean',
    tooltip: 'Check if the company account is active. Inactive companies may have restricted access.',
  },
};

export function getFieldInfo(field: ConditionField): FieldInfo {
  return fieldInfoMap[field] || {
    label: field,
    category: 'Other',
    description: 'Custom field',
    examples: [],
    valueType: 'text',
    tooltip: 'Custom field condition',
  };
}

export function getFieldsByCategory() {
  const categories: Record<string, ConditionField[]> = {};
  Object.entries(fieldInfoMap).forEach(([field, info]) => {
    if (!categories[info.category]) {
      categories[info.category] = [];
    }
    categories[info.category].push(field as ConditionField);
  });
  return categories;
}


