// Assemblies Registry - Seed assemblies for UK domestic construction

import type { Assembly } from './types';

export const seedAssemblies: Assembly[] = [
  {
    id: 'strip-foundations',
    name: 'Strip Foundations',
    category: 'Groundworks',
    defaultUnit: 'lm',
    description: 'Standard strip foundations per linear metre',
    lines: [
      {
        id: 'foundations-excavate',
        title: 'Excavate foundations',
        costType: 'labour',
        qtyFormula: '{perimeterM}',
        unit: 'lm',
        baseUnitCost: 45.0,
        defaultMarkupPct: 15.0,
        vatApplicable: true,
        customerTextBlock: 'Excavation for strip foundations',
      },
      {
        id: 'foundations-concrete',
        title: 'Concrete for foundations',
        costType: 'material',
        qtyFormula: '{perimeterM} * 0.5',
        unit: 'm³',
        baseUnitCost: 120.0,
        defaultMarkupPct: 15.0,
        vatApplicable: true,
        customerTextBlock: 'Ready-mix concrete C25/30',
      },
      {
        id: 'foundations-place',
        title: 'Place and level concrete',
        costType: 'labour',
        qtyFormula: '{perimeterM} * 0.5',
        unit: 'm³',
        baseUnitCost: 35.0,
        defaultMarkupPct: 15.0,
        vatApplicable: true,
        customerTextBlock: 'Place and finish concrete',
      },
    ],
  },
  {
    id: 'concrete-slab',
    name: 'Concrete Slab',
    category: 'Groundworks',
    defaultUnit: 'm²',
    description: 'Concrete floor slab per square metre',
    lines: [
      {
        id: 'slab-hardcore',
        title: 'Hardcore and blinding',
        costType: 'material',
        qtyFormula: '{floorAreaM2}',
        unit: 'm²',
        baseUnitCost: 12.0,
        defaultMarkupPct: 15.0,
        vatApplicable: true,
        customerTextBlock: 'Hardcore and sand blinding',
      },
      {
        id: 'slab-concrete',
        title: 'Concrete slab',
        costType: 'material',
        qtyFormula: '{floorAreaM2} * 0.15',
        unit: 'm³',
        baseUnitCost: 120.0,
        defaultMarkupPct: 15.0,
        vatApplicable: true,
        customerTextBlock: 'Concrete floor slab 150mm thick',
      },
      {
        id: 'slab-reinforcement',
        title: 'Reinforcement mesh',
        costType: 'material',
        qtyFormula: '{floorAreaM2}',
        unit: 'm²',
        baseUnitCost: 8.0,
        defaultMarkupPct: 15.0,
        vatApplicable: true,
        customerTextBlock: 'A142 reinforcement mesh',
      },
    ],
  },
  {
    id: 'external-cavity-wall',
    name: 'External Cavity Wall',
    category: 'Structure',
    defaultUnit: 'm²',
    description: 'External cavity wall construction per square metre',
    lines: [
      {
        id: 'wall-blocks',
        title: 'Blockwork inner leaf',
        costType: 'material',
        qtyFormula: '{externalWallAreaM2}',
        unit: 'm²',
        baseUnitCost: 25.0,
        defaultMarkupPct: 15.0,
        vatApplicable: true,
        customerTextBlock: '100mm dense concrete blocks',
      },
      {
        id: 'wall-insulation',
        title: 'Cavity insulation',
        costType: 'material',
        qtyFormula: '{externalWallAreaM2}',
        unit: 'm²',
        baseUnitCost: 12.0,
        defaultMarkupPct: 15.0,
        vatApplicable: true,
        customerTextBlock: '100mm cavity wall insulation',
      },
      {
        id: 'wall-build',
        title: 'Build walls',
        costType: 'labour',
        qtyFormula: '{externalWallAreaM2}',
        unit: 'm²',
        baseUnitCost: 40.0,
        defaultMarkupPct: 15.0,
        vatApplicable: true,
        customerTextBlock: 'Blockwork construction',
      },
    ],
  },
  {
    id: 'flat-roof-warm-deck',
    name: 'Flat Roof - Warm Deck',
    category: 'Roofing',
    defaultUnit: 'm²',
    description: 'Flat roof warm deck construction per square metre',
    lines: [
      {
        id: 'flat-roof-structure',
        title: 'Roof structure timber',
        costType: 'material',
        qtyFormula: '{roofAreaM2}',
        unit: 'm²',
        baseUnitCost: 35.0,
        defaultMarkupPct: 15.0,
        vatApplicable: true,
        customerTextBlock: 'Timber joists and decking',
      },
      {
        id: 'flat-roof-insulation',
        title: 'Insulation',
        costType: 'material',
        qtyFormula: '{roofAreaM2}',
        unit: 'm²',
        baseUnitCost: 18.0,
        defaultMarkupPct: 15.0,
        vatApplicable: true,
        customerTextBlock: 'Warm deck insulation',
      },
      {
        id: 'flat-roof-covering',
        title: 'Roof covering',
        costType: 'material',
        qtyFormula: '{roofAreaM2}',
        unit: 'm²',
        baseUnitCost: 25.0,
        defaultMarkupPct: 15.0,
        vatApplicable: true,
        customerTextBlock: 'EPDM or GRP roofing system',
      },
      {
        id: 'flat-roof-labour',
        title: 'Construct flat roof',
        costType: 'labour',
        qtyFormula: '{roofAreaM2}',
        unit: 'm²',
        baseUnitCost: 45.0,
        defaultMarkupPct: 15.0,
        vatApplicable: true,
        customerTextBlock: 'Flat roof construction',
      },
    ],
  },
  {
    id: 'pitched-roof-covering',
    name: 'Pitched Roof Covering',
    category: 'Roofing',
    defaultUnit: 'm²',
    description: 'Pitched roof covering per square metre',
    lines: [
      {
        id: 'pitched-roof-structure',
        title: 'Roof structure timber',
        costType: 'material',
        qtyFormula: '{roofAreaM2}',
        unit: 'm²',
        baseUnitCost: 40.0,
        defaultMarkupPct: 15.0,
        vatApplicable: true,
        customerTextBlock: 'Pitched roof structure',
      },
      {
        id: 'pitched-roof-tiles',
        title: 'Roof covering',
        costType: 'material',
        qtyFormula: '{roofAreaM2}',
        unit: 'm²',
        baseUnitCost: 45.0,
        defaultMarkupPct: 15.0,
        vatApplicable: true,
        customerTextBlock: 'Slate or tile covering',
      },
      {
        id: 'pitched-roof-labour',
        title: 'Construct pitched roof',
        costType: 'labour',
        qtyFormula: '{roofAreaM2}',
        unit: 'm²',
        baseUnitCost: 55.0,
        defaultMarkupPct: 15.0,
        vatApplicable: true,
        customerTextBlock: 'Pitched roof construction',
      },
    ],
  },
  {
    id: 'plasterboard-skim',
    name: 'Plasterboard & Skim',
    category: 'Finishes',
    defaultUnit: 'm²',
    description: 'Plasterboard and skim finish per square metre',
    lines: [
      {
        id: 'plasterboard-board',
        title: 'Plasterboard',
        costType: 'material',
        qtyFormula: '{externalWallAreaM2} * 1.5',
        unit: 'm²',
        baseUnitCost: 8.0,
        defaultMarkupPct: 15.0,
        vatApplicable: true,
        customerTextBlock: 'Plasterboard sheets',
      },
      {
        id: 'plasterboard-skim',
        title: 'Plastering',
        costType: 'labour',
        qtyFormula: '{externalWallAreaM2} * 1.5',
        unit: 'm²',
        baseUnitCost: 12.0,
        defaultMarkupPct: 15.0,
        vatApplicable: true,
        customerTextBlock: 'Plaster and skim finish',
      },
    ],
  },
  {
    id: 'first-fix-electrics',
    name: 'First Fix Electrics',
    category: 'Services',
    defaultUnit: 'm²',
    description: 'First fix electrical installation per square metre',
    lines: [
      {
        id: 'electrics-materials',
        title: 'Electrical materials',
        costType: 'material',
        qtyFormula: '{floorAreaM2}',
        unit: 'm²',
        baseUnitCost: 15.0,
        defaultMarkupPct: 15.0,
        vatApplicable: true,
        customerTextBlock: 'Cables, sockets, switches, consumer unit',
      },
      {
        id: 'electrics-labour',
        title: 'First fix electrical installation',
        costType: 'subcontract',
        qtyFormula: '{floorAreaM2}',
        unit: 'm²',
        baseUnitCost: 45.0,
        defaultMarkupPct: 15.0,
        vatApplicable: true,
        customerTextBlock: 'First fix electrical work',
      },
    ],
  },
  {
    id: 'heating-allowance',
    name: 'Heating Allowance',
    category: 'Services',
    defaultUnit: 'm²',
    description: 'Heating installation allowance per square metre',
    lines: [
      {
        id: 'heating-materials',
        title: 'Heating materials',
        costType: 'material',
        qtyFormula: '{floorAreaM2}',
        unit: 'm²',
        baseUnitCost: 20.0,
        defaultMarkupPct: 15.0,
        vatApplicable: true,
        customerTextBlock: 'Radiators, pipework, fittings',
      },
      {
        id: 'heating-labour',
        title: 'Heating installation',
        costType: 'subcontract',
        qtyFormula: '{floorAreaM2}',
        unit: 'm²',
        baseUnitCost: 50.0,
        defaultMarkupPct: 15.0,
        vatApplicable: true,
        customerTextBlock: 'Heating installation',
      },
    ],
  },
  {
    id: 'waste-skips',
    name: 'Waste / Skips',
    category: 'Preliminaries',
    defaultUnit: 'no',
    description: 'Waste removal and skip hire',
    lines: [
      {
        id: 'skip-hire',
        title: 'Skip hire',
        costType: 'prelim',
        qtyFormula: '1',
        unit: 'no',
        baseUnitCost: 250.0,
        defaultMarkupPct: 0.0,
        vatApplicable: true,
        customerTextBlock: 'Skip hire and waste removal',
      },
    ],
  },
  {
    id: 'scaffolding',
    name: 'Scaffolding',
    category: 'Preliminaries',
    defaultUnit: 'no',
    description: 'Scaffolding provision (provisional sum)',
    lines: [
      {
        id: 'scaffolding-provisional',
        title: 'Scaffolding',
        costType: 'prelim',
        qtyFormula: '1',
        unit: 'no',
        baseUnitCost: 800.0,
        defaultMarkupPct: 0.0,
        vatApplicable: true,
        customerTextBlock: 'Scaffolding provision (provisional sum)',
      },
    ],
  },
];

// Helper to get assembly by ID
export function getAssemblyById(id: string): Assembly | undefined {
  return seedAssemblies.find((a) => a.id === id);
}

// Helper to get assemblies by category
export function getAssembliesByCategory(category: string): Assembly[] {
  return seedAssemblies.filter((a) => a.category === category);
}

