import type { CalculatorSchema, CalculatorOutput } from './estimating.schemas';

export const seedAssemblies = [
  {
    key: 'plaster_walls_v1',
    name: 'Plasterboard + Skim (Walls)',
    category: 'Plastering',
    description: 'Area-based wall lining + skim finish.',
    items: [
      {
        sort_order: 0,
        item_type: 'material',
        title: 'Plasterboard 12.5mm (supply)',
        quantity_expr: 'area',
        unit: 'm2',
        unit_cost: 3.50,
        margin_percent: 25,
        is_client_visible: true,
      },
      {
        sort_order: 1,
        item_type: 'labour',
        title: 'Fix boards + skim finish',
        quantity_expr: 'area',
        unit: 'm2',
        unit_cost: 12.00,
        margin_percent: 30,
        is_client_visible: true,
      },
    ],
  },
  {
    key: 'floor_screed_v1',
    name: 'Floor Screed (Traditional)',
    category: 'Floors',
    description: 'Area + thickness calculation for screed.',
    items: [
      {
        sort_order: 0,
        item_type: 'material',
        title: 'Screed materials (sand/cement mix)',
        quantity_expr: 'area * thickness',  // thickness in metres
        unit: 'm3',
        unit_cost: 95.00,
        margin_percent: 20,
        is_client_visible: true,
      },
      {
        sort_order: 1,
        item_type: 'labour',
        title: 'Lay and finish screed',
        quantity_expr: 'area',
        unit: 'm2',
        unit_cost: 10.00,
        margin_percent: 25,
        is_client_visible: true,
      },
    ],
  },
  {
    key: 'block_wall_v1',
    name: 'Block/Brick Wall',
    category: 'Masonry',
    description: 'Length x height less openings.',
    items: [
      {
        sort_order: 0,
        item_type: 'material',
        title: 'Blocks/Bricks (supply)',
        quantity_expr: 'netArea',
        unit: 'm2',
        unit_cost: 18.00,
        margin_percent: 20,
        is_client_visible: true,
      },
      {
        sort_order: 1,
        item_type: 'labour',
        title: 'Build wall',
        quantity_expr: 'netArea',
        unit: 'm2',
        unit_cost: 35.00,
        margin_percent: 25,
        is_client_visible: true,
      },
    ],
  },
  {
    key: 'kitchen_cabinets_v1',
    name: 'Kitchen Base Units',
    category: 'Kitchen',
    description: 'Standard kitchen base units with worktop.',
    items: [
      {
        sort_order: 0,
        item_type: 'material',
        title: 'Kitchen base units (supply)',
        quantity_expr: 'units',
        unit: 'each',
        unit_cost: 150.00,
        margin_percent: 30,
        is_client_visible: true,
      },
      {
        sort_order: 1,
        item_type: 'labour',
        title: 'Install base units',
        quantity_expr: 'units',
        unit: 'each',
        unit_cost: 80.00,
        margin_percent: 35,
        is_client_visible: true,
      },
      {
        sort_order: 2,
        item_type: 'material',
        title: 'Worktop (supply)',
        quantity_expr: 'length',
        unit: 'm',
        unit_cost: 120.00,
        margin_percent: 25,
        is_client_visible: true,
      },
      {
        sort_order: 3,
        item_type: 'labour',
        title: 'Install worktop',
        quantity_expr: 'length',
        unit: 'm',
        unit_cost: 60.00,
        margin_percent: 30,
        is_client_visible: true,
      },
    ],
  },
  {
    key: 'bathroom_tiling_v1',
    name: 'Bathroom Wall Tiling',
    category: 'Bathroom',
    description: 'Wall tiling for bathroom including adhesive and grout.',
    items: [
      {
        sort_order: 0,
        item_type: 'material',
        title: 'Wall tiles (supply)',
        quantity_expr: 'area',
        unit: 'm2',
        unit_cost: 35.00,
        margin_percent: 30,
        is_client_visible: true,
      },
      {
        sort_order: 1,
        item_type: 'material',
        title: 'Tile adhesive and grout',
        quantity_expr: 'area',
        unit: 'm2',
        unit_cost: 8.00,
        margin_percent: 25,
        is_client_visible: true,
      },
      {
        sort_order: 2,
        item_type: 'labour',
        title: 'Tile walls',
        quantity_expr: 'area',
        unit: 'm2',
        unit_cost: 45.00,
        margin_percent: 35,
        is_client_visible: true,
      },
    ],
  },
  {
    key: 'electrical_ring_main_v1',
    name: 'Electrical Ring Main',
    category: 'Electrical',
    description: 'New ring main circuit installation.',
    items: [
      {
        sort_order: 0,
        item_type: 'material',
        title: '2.5mm T&E cable',
        quantity_expr: 'length',
        unit: 'm',
        unit_cost: 2.50,
        margin_percent: 25,
        is_client_visible: true,
      },
      {
        sort_order: 1,
        item_type: 'material',
        title: 'Consumer unit components',
        quantity_expr: '1',
        unit: 'circuit',
        unit_cost: 85.00,
        margin_percent: 30,
        is_client_visible: true,
      },
      {
        sort_order: 2,
        item_type: 'labour',
        title: 'Install ring main',
        quantity_expr: 'length',
        unit: 'm',
        unit_cost: 15.00,
        margin_percent: 40,
        is_client_visible: true,
      },
    ],
  },
  {
    key: 'plumbing_radiator_v1',
    name: 'Radiator Installation',
    category: 'Plumbing',
    description: 'Install new radiator with pipework.',
    items: [
      {
        sort_order: 0,
        item_type: 'material',
        title: 'Radiator (supply)',
        quantity_expr: '1',
        unit: 'each',
        unit_cost: 120.00,
        margin_percent: 30,
        is_client_visible: true,
      },
      {
        sort_order: 1,
        item_type: 'material',
        title: 'Pipework and fittings',
        quantity_expr: '1',
        unit: 'each',
        unit_cost: 45.00,
        margin_percent: 25,
        is_client_visible: true,
      },
      {
        sort_order: 2,
        item_type: 'labour',
        title: 'Install radiator',
        quantity_expr: '1',
        unit: 'each',
        unit_cost: 150.00,
        margin_percent: 35,
        is_client_visible: true,
      },
    ],
  },
] as const;

export const seedCalculators: Array<{
  key: string;
  name: string;
  category: string;
  description: string;
  schema: CalculatorSchema;
  output: Omit<CalculatorOutput, 'assemblyId'> & { assemblyKey: string };
}> = [
  {
    key: 'calc_plaster_walls_v1',
    name: 'Plasterboard + Skim (Walls)',
    category: 'Plastering',
    description: 'Enter wall area to generate estimate items.',
    schema: {
      version: 1,
      fields: [
        { key: 'area', label: 'Wall area', type: 'number', unit: 'm2', required: true, min: 0, step: 0.1, defaultValue: 20 },
      ],
    },
    output: { version: 1, variables: ['area'], assemblyKey: 'plaster_walls_v1' },
  },
  {
    key: 'calc_floor_screed_v1',
    name: 'Floor Screed',
    category: 'Floors',
    description: 'Area + thickness to generate screed items.',
    schema: {
      version: 1,
      fields: [
        { key: 'area', label: 'Floor area', type: 'number', unit: 'm2', required: true, min: 0, step: 0.1, defaultValue: 30 },
        { key: 'thickness', label: 'Thickness', type: 'number', unit: 'mm', required: true, min: 10, step: 1, defaultValue: 50 },
      ],
    },
    output: { version: 1, variables: ['area', 'thickness'], assemblyKey: 'floor_screed_v1' },
  },
  {
    key: 'calc_block_wall_v1',
    name: 'Wall (Length × Height − Openings)',
    category: 'Masonry',
    description: 'Generate wall items by net area.',
    schema: {
      version: 1,
      fields: [
        { key: 'length', label: 'Length', type: 'number', unit: 'm', required: true, min: 0, step: 0.1, defaultValue: 6 },
        { key: 'height', label: 'Height', type: 'number', unit: 'm', required: true, min: 0, step: 0.1, defaultValue: 2.4 },
        { key: 'openingsArea', label: 'Openings area (doors/windows)', type: 'number', unit: 'm2', required: true, min: 0, step: 0.1, defaultValue: 1.8 },
      ],
    },
    output: { version: 1, variables: ['netArea'], assemblyKey: 'block_wall_v1' },
  },
];

